services:
  claude-cli:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: claude-cli
    volumes:
      # Mount .env file for API keys (create this file locally)
      - ./.env:/app/.env:ro
      # Mount source code for development (optional)
      - ./src:/app/src:ro
      # Mount config for runtime changes
      - ./config.json:/app/config.json:ro
      # Mount sandbox directory for assistant working area
      - ./sandbox:/app/sandbox:rw
    environment:
      - PYTHONPATH=/app/src
    # Security options
    security_opt:
      - no-new-privileges:true
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
    # Network isolation
    networks:
      - claude-network
    # Restart policy
    restart: unless-stopped
    # Remove container when stopped
    stdin_open: true
    tty: true

  # Optional: Add a development service with more permissions
  claude-cli-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: claude-cli-dev
    volumes:
      - ./.env:/app/.env:ro
      - ./src:/app/src
      - ./tests:/app/tests
      - ./config.json:/app/config.json
      # Mount sandbox directory for assistant working area
      - ./sandbox:/app/sandbox:rw
    environment:
      - PYTHONPATH=/app/src
    security_opt:
      - no-new-privileges:true
    networks:
      - claude-network
    stdin_open: true
    tty: true
    # Override command for development
    command: /bin/bash

networks:
  claude-network:
    driver: bridge
    # Isolate from other Docker networks
    internal: false
