name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Verify test environment safety
      run: |
        echo "Verifying no real API keys are used..."
        if [[ "$ANTHROPIC_API_KEY" == *"sk-"* ]]; then
          echo "ERROR: Real API key detected in CI environment!"
          exit 1
        fi
        echo "✓ Safe test API key confirmed"
      env:
        ANTHROPIC_API_KEY: test-key-for-ci-no-real-calls

    - name: Lint with ruff
      run: |
        ruff check .
        ruff format --check .

    - name: Test with pytest
      run: |
        pytest tests/ -v --tb=short
      env:
        ANTHROPIC_API_KEY: test-key-for-ci-no-real-calls
        PYTEST_DISABLE_PLUGIN_AUTOLOAD: 1

  code-quality:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run pre-commit hooks
      run: |
        pip install pre-commit
        pre-commit run --all-files
      env:
        ANTHROPIC_API_KEY: test-key-for-ci-no-real-calls
